// server api requests
export const GET_ROUTE_ADMIN = 'GET_ROUTE_ADMIN'
export const SAVE_ROUTE_EDITS = 'SAVE_ROUTE_EDITS'

// edit data
export const EDIT_ROUTE_POINT = 'EDIT_ROUTE_POINT'
export const DELETE_ROUTE_ENTRY = 'DELETE_ROUTE_ENTRY'
export const MOVE_ROUTE_POINT_UP_IN_ARRAY = 'MOVE_ROUTE_POINT_UP_IN_ARRAY'

// create new route point
export const SET_NEW_ROUTE_DIALOG_OPEN = 'SET_NEW_ROUTE_DIALOG_OPEN'
export const SAVE_NEW_ROUTE_POINT = 'SAVE_NEW_ROUTE_POINT'
export const UPDATE_NEW_ROUTE_POINT_FORM = 'UPDATE_NEW_ROUTE_POINT_FORM'
export const RESET_NEW_ROUTE_POINT_FORM = 'RESET_NEW_ROUTE_POINT_FORM'
export const HIDE_NEW_ROUTE_POINT_SNACKBAR = 'HIDE_NEW_ROUTE_POINT_SNACKBAR'

// Other
export const HOVER_ADMIN_ROUTE_POINT = 'HOVER_ADMIN_ROUTE_POINT'
