// server api requests
export const GET_ROUTE_ADMIN = 'GET_ROUTE_ADMIN'
export const SAVE_ROUTE_EDITS = 'SAVE_ROUTE_EDITS'

// edit data
export const EDIT_ROUTE_POINT = 'EDIT_ROUTE_POINT'
export const DELETE_ROUTE_ENTRY = 'DELETE_ROUTE_ENTRY'

// create new route point
export const SET_NEW_ROUTE_DIALOG_OPEN = 'SET_NEW_ROUTE_DIALOG_OPEN'
export const SAVE_NEW_ROUTE_POINT = 'SAVE_NEW_ROUTE_POINT'
export const UPDATE_NEW_ROUTE_POINT_FORM = 'UPDATE_NEW_ROUTE_POINT_FORM'
export const RESET_NEW_ROUTE_POINT_FORM = 'RESET_NEW_ROUTE_POINT_FORM'
export const HIDE_NEW_ROUTE_POINT_SNACKBAR = 'HIDE_NEW_ROUTE_POINT_SNACKBAR'

// Map controls
export const ON_ROUTE_MAP_CHANGE = 'ON_ROUTE_MAP_CHANGE'
export const ON_ROUTE_ADMIN_MAP_LOAD = 'ON_ROUTE_ADMIN_MAP_LOAD'
export const ON_ROUTE_G_MAP_INSTANCE_UPDATE = 'ON_ROUTE_G_MAP_INSTANCE_UPDATE'

// Other
export const HOVER_ADMIN_ROUTE_POINT = 'HOVER_ADMIN_ROUTE_POINT'
