// Server requests
export const SAVE_NEW_BLOG_ENTRY = 'SAVE_NEW_BLOG_ENTRY'
export const DELETE_BLOG_ENTRY = 'DELETE_BLOG_ENTRY'

// New blog entry form
export const UPDATE_NEW_BLOG_ENTRY_FORM = 'UPDATE_NEW_BLOG_ENTRY_FORM'
export const TOGGLE_NEW_BLOG_ENTRY_PROP = 'TOGGLE_NEW_BLOG_ENTRY_PROP'
export const MOVE_NEW_BLOG_PHOTO_UP_IN_ARRAY = 'MOVE_NEW_BLOG_PHOTO_UP_IN_ARRAY'
export const ON_NEW_BLOG_PHOTO_EDIT = 'ON_NEW_BLOG_PHOTO_EDIT'
export const SAVE_NEW_BLOG_PHOTOS_EDITS = 'SAVE_NEW_BLOG_PHOTOS_EDITS'
