
export const UPDATE_PHOTO_UPLOADER_PROP = 'UPDATE_PHOTO_UPLOADER_PROP'
export const UPLOAD_NEW_BLOG_PHOTOS = 'UPLOAD_NEW_BLOG_PHOTOS'
export const UPDATE_UPLOADED_PHOTO = 'UPDATE_UPLOADED_PHOTO'
export const CANCEL_PHOTO_UPLOAD = 'CANCEL_PHOTO_UPLOAD'
export const SAVE_UPLOADED_PHOTOS = 'SAVE_UPLOADED_PHOTOS'
