
export const UPDATE_PHOTO_UPLOADER_PROP = 'UPDATE_PHOTO_UPLOADER_PROP'
export const UPLOAD_NEW_BLOG_PHOTOS = 'UPLOAD_NEW_BLOG_PHOTOS'
export const UPDATE_UPLOADED_PHOTO = 'UPDATE_UPLOADED_PHOTO'
export const UPDATE_UPLOADED_PHOTO_DATABASE = 'UPDATE_UPLOADED_PHOTO_DATABASE'
export const CANCEL_PHOTO_UPLOAD = 'CANCEL_PHOTO_UPLOAD'
export const SAVE_UPLOADED_PHOTOS = 'SAVE_UPLOADED_PHOTOS'
export const UPLOAD_PHOTO_TO_SERVER = 'UPLOAD_PHOTO_TO_SERVER'
export const UPLOAD_PHOTO_TO_S3 = 'UPLOAD_PHOTO_TO_S3'
