
// Map actions
export const ON_MAP_CHANGE = 'ON_MAP_CHANGE'
export const ON_GOOGLE_API_LOADED = 'ON_GOOGLE_API_LOADED'
export const ON_MAP_CLICK = 'ON_MAP_CLICK'
export const ON_MAP_CHILD_CLICK = 'ON_MAP_CHILD_CLICK'
export const ON_MAP_SPECIFIC_CHILD_CLICK = 'ON_MAP_SPECIFIC_CHILD_CLICK'
